In [2]:
import numpy as np
import pandas as pd

In [3]:
array1 = np.array([22,43,23,45,65,75,9])
array2 = np.array([87,32,45,35,2,76,96,])

In [4]:
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition of Array 1 & Array2:", addition)
print("Subtraction of Array 1 & Array2:", subtraction)
print("Multiplication of Array 1 & Array2:", multiplication)
print("Division of Array 1 & Array2:", division)

Addition of Array 1 & Array2: [109  75  68  80  67 151 105]
Subtraction of Array 1 & Array2: [-65  11 -22  10  63  -1 -87]
Multiplication of Array 1 & Array2: [1914 1376 1035 1575  130 5700  864]
Division of Array 1 & Array2: [ 0.25287356  1.34375     0.51111111  1.28571429 32.5         0.98684211
  0.09375   ]


In [10]:
df = pd.read_csv('retail supermarket.csv')
df

Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky   
1       Second Class   Consumer  United States        Henderson    Kentucky   
2       Second Class  Corporate  United States      Los Angeles  California   
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
...              ...        ...            ...              ...         ...   
9989    Second Class   Consumer  United States            Miami     Florida   
9990  Standard Class   Consumer  United States       Costa Mesa  California   
9991  Standard Class   Consumer  United States       Costa Mesa  California   
9992  Standard Class   Consumer  United States       Costa Mesa  California   
9993    Second Class   Consumer  United States      Westminster  California   

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2   
1           42420  South        Furniture       Chairs  731.9400         3   
2           90036   West  Office Supplies       Labels   14.6200         2   
3           33311  South        Furniture       Tables  957.5775         5   
4           33311  South  Office Supplies      Storage   22.3680         2   
...           ...    ...              ...          ...       ...       ...   
9989        33180  South        Furniture  Furnishings   25.2480         3   
9990        92627   West        Furniture  Furnishings   91.9600         2   
9991        92627   West       Technology       Phones  258.5760         2   
9992        92627   West  Office Supplies        Paper   29.6000         4   
9993        92683   West  Office Supplies   Appliances  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.00   13.3200  
9993      0.00   72.9480  

[9994 rows x 13 columns]

In [12]:
df.head()

Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky   
1    Second Class   Consumer  United States        Henderson    Kentucky   
2    Second Class  Corporate  United States      Los Angeles  California   
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida   

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2   
1        42420  South        Furniture       Chairs  731.9400         3   
2        90036   West  Office Supplies       Labels   14.6200         2   
3        33311  South        Furniture       Tables  957.5775         5   
4        33311  South  Office Supplies      Storage   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164

In [14]:
df.head(10)


Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky   
1    Second Class   Consumer  United States        Henderson    Kentucky   
2    Second Class  Corporate  United States      Los Angeles  California   
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
5  Standard Class   Consumer  United States      Los Angeles  California   
6  Standard Class   Consumer  United States      Los Angeles  California   
7  Standard Class   Consumer  United States      Los Angeles  California   
8  Standard Class   Consumer  United States      Los Angeles  California   
9  Standard Class   Consumer  United States      Los Angeles  California   

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2   
1        42420  South        Furniture       Chairs  731.9400         3   
2        90036   West  Office Supplies       Labels   14.6200         2   
3        33311  South        Furniture       Tables  957.5775         5   
4        33311  South  Office Supplies      Storage   22.3680         2   
5        90032   West        Furniture  Furnishings   48.8600         7   
6        90032   West  Office Supplies          Art    7.2800         4   
7        90032   West       Technology       Phones  907.1520         6   
8        90032   West  Office Supplies      Binders   18.5040         3   
9        90032   West  Office Supplies   Appliances  114.9000         5   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  
5      0.00   14.1694  
6      0.00    1.9656  
7      0.20   90.7152  
8      0.20    5.7825  
9      0.00   34.4700

In [16]:
df.tail(2)

Ship Mode   Segment        Country         City       State  \
9992  Standard Class  Consumer  United States   Costa Mesa  California   
9993    Second Class  Consumer  United States  Westminster  California   

      Postal Code Region         Category Sub-Category   Sales  Quantity  \
9992        92627   West  Office Supplies        Paper   29.60         4   
9993        92683   West  Office Supplies   Appliances  243.16         2   

      Discount  Profit  
9992       0.0  13.320  
9993       0.0  72.948

In [24]:
df.loc[0]

Ship Mode        Second Class
Segment              Consumer
Country         United States
City                Henderson
State                Kentucky
Postal Code             42420
Region                  South
Category            Furniture
Sub-Category        Bookcases
Sales                  261.96
Quantity                    2
Discount                  0.0
Profit                41.9136
Name: 0, dtype: object

In [43]:
df.loc[45:50,'City':'Quantity']

City      State  Postal Code   Region         Category Sub-Category  \
45       Eagan  Minnesota        55122  Central  Office Supplies      Binders   
46    Westland   Michigan        48185  Central  Office Supplies      Storage   
47       Dover   Delaware        19901     East       Technology  Accessories   
48       Dover   Delaware        19901     East       Technology       Phones   
49  New Albany    Indiana        47150  Central  Office Supplies      Binders   
50  New Albany    Indiana        47150  Central  Office Supplies       Labels   

     Sales  Quantity  
45   17.46         2  
46  211.96         4  
47   45.00         3  
48   21.80         2  
49   38.22         6  
50   75.18         6

In [47]:
df.iloc[47]

Ship Mode       Standard Class
Segment               Consumer
Country          United States
City                     Dover
State                 Delaware
Postal Code              19901
Region                    East
Category            Technology
Sub-Category       Accessories
Sales                     45.0
Quantity                     3
Discount                   0.0
Profit                    4.95
Name: 47, dtype: object

In [83]:
array3 = np.array([4,5,6,7,10,9,8,11,12])

In [85]:
np.mean(array3)

8.0

In [87]:
np.median(array3)

8.0

In [91]:
np.var(array3)

6.666666666666667

In [93]:
np.std(array3)

2.581988897471611

In [98]:
arr_int = np.array([3,5,6,4,7,8,6,2])
arr_float = np.array([2.5,7.6,7.7,8.3,8.2,4.4,5.2,4.9])
arr_bool = np.array([True,False,False,True,False,True,True,False])

In [104]:
arr1 = np.array([1,3,8,5,3])
arr2 = np.array([3,6,7,8,9])

In [110]:
conc_arr = np.concatenate((arr1,arr2))
conc_arr

array([1, 3, 8, 5, 3, 3, 6, 7, 8, 9])

In [112]:
sort_asc = np.sort(arr1)
sort_asc

array([1, 3, 3, 5, 8])

In [122]:
sort_desc = np.sort(arr1)[::-1]
sort_desc

array([8, 5, 3, 3, 1])